//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc_lesson2._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooksTable
    {
        public string BookName { get; set; }
        public double BookPrice { get; set; }
        public string WritersNameSurname { get; set; }
        public int ID { get; set; }
        public string BookPhoto { get; set; }
    }
}
